### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by kevin700523** [ArrowJustDoIt/dcat-admin-crontab-extension#1]
`Package operations: 1 install, 0 updates, 0 removals
  - Downloading arrowjustdoit/dcat-admin-crontab-extension (0.0.1)
  - Installing arrowjustdoit/dcat-admin-crontab-extension (0.0.1): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Fatal error:  Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in /Users/KevinLiu/code/vendor/arrowjustdoit/dcat-admin-crontab-extension/src/bootstrap.php:4
Stack trace:
#0 /Users/KevinLiu/code/vendor/composer/autoload_real.php(71): require()
#1 /Users/KevinLiu/code/vendor/composer/autoload_real.php(61): composerRequireca0b1601e02563ca7231536bc89f5aa3('4bc9eb8c1c395cc...', '/Users/KevinLiu...')
#2 /Users/KevinLiu/code/vendor/autoload.php(7): ComposerAutoloaderInitca0b1601e02563ca7231536bc89f5aa3::getLoader()
#3 /Users/KevinLiu/code/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/Users/KevinLiu...')
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(322): Illuminate\Foundation\ComposerScripts::postAutoloadDump(Object(Composer\Script\Event))
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(218): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Illum in /Users/KevinLiu/code/vendor/arrowjustdoit/dcat-admin-crontab-extension/src/bootstrap.php on line 4

Fatal error: Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in /Users/KevinLiu/code/vendor/arrowjustdoit/dcat-admin-crontab-extension/src/bootstrap.php:4
Stack trace:
#0 /Users/KevinLiu/code/vendor/composer/autoload_real.php(71): require()
#1 /Users/KevinLiu/code/vendor/composer/autoload_real.php(61): composerRequireca0b1601e02563ca7231536bc89f5aa3('4bc9eb8c1c395cc...', '/Users/KevinLiu...')
#2 /Users/KevinLiu/code/vendor/autoload.php(7): ComposerAutoloaderInitca0b1601e02563ca7231536bc89f5aa3::getLoader()
#3 /Users/KevinLiu/code/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/Users/KevinLiu...')
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(322): Illuminate\Foundation\ComposerScripts::postAutoloadDump(Object(Composer\Script\Event))
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(218): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Illum in /Users/KevinLiu/code/vendor/arrowjustdoit/dcat-admin-crontab-extension/src/bootstrap.php on line 4`

**Comment by warmup413** [comment]
遇到一样的问题

**Comment by muzidudu** [comment]
+1

**Comment by gyp719** [comment]
+1

[Error]
  Call to undefined method Dcat\Admin\Admin::extend()

![Uploading image.png…]()

**Comment by lifetin** [comment]
+1


```
In bootstrap.php line 4:

  [Error]
  Call to undefined method Dcat\Admin\Admin::extend()


Exception trace:
  at D:\workspace\work\gaoxin\lunwen\web-php\vendor\arrowjustdoit\dcat-admin-crontab-extension\src\bootstrap.php:4
 require() at D:\workspace\work\gaoxin\lunwen\web-php\vendor\composer\autoload_real.php:41
```

**Comment by CamilaWeiLu** [comment]
+1
